.TH CLIP_UPDATE_USER_DATA 8 "OCT 2007" Linux "User Manuals"
.SH NAME
clip-update-user-data \- updates user data.
.SH SYNOPSIS
.B clip-update-user-data
[\-h] |\-v] 
.SH DESCRIPTION
.B clip-update-user-data
performs user data updates. 

.B clip-update-user-data
is a script intended to be run non-interactively.

.SH OPTIONS
.IP \-h
Print help and exit
.IP \-v
Print version of the utility and exit
.SH DIAGNOSTICS
The script returns 0 if no error occured.
.SH AUTHORS
EADS Defence And Security Systems
